name: Java CI with Gradle - Test Automation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write  # 테스트 결과 보고서를 위한 권한

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # gradlew 실행 권한 부여 (Ubuntu 환경에서 필요)
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      if: runner.os != 'Windows'

    # 캐시를 사용하여 빌드 시간 단축
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 컴파일 확인
    - name: Compile Java code
      run: |
        echo "🔨 Compiling Java source and test code..."
        ./gradlew compileJava compileTestJava --no-daemon --stacktrace
      continue-on-error: false

    # 테스트 실행 (JUnit 5 기반)
    - name: Run JUnit Tests
      run: |
        echo "🧪 Running JUnit 5 tests..."
        ./gradlew test --no-daemon --stacktrace || echo "Some tests failed, but continuing..."
      continue-on-error: true

    # 커스텀 테스트 실행 (BasicTest.java)
    - name: Run BasicTest
      run: |
        echo "🎮 Running BasicTest for Tetris game requirements..."
        if [ -f "build/classes/java/test/tetris/BasicTest.class" ]; then
          java -cp "build/classes/java/main:build/classes/java/test" tetris.BasicTest || echo "BasicTest completed with warnings"
        else
          echo "BasicTest.class not found, skipping..."
        fi
      continue-on-error: true

    # 커스텀 테스트 실행 (GameScreenTest.java) - 존재하는 경우에만
    - name: Run GameScreenTest
      run: |
        echo "🖥️ Running GameScreenTest for UI requirements..."
        if [ -f "build/classes/java/test/tetris/GameScreenTest.class" ]; then
          java -cp "build/classes/java/main:build/classes/java/test" tetris.GameScreenTest || echo "GameScreenTest completed with warnings"
        else
          echo "GameScreenTest.class not found, skipping..."
        fi
      continue-on-error: true

    # 테스트 결과 보고서 생성 (테스트가 실행된 경우에만)
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always() && hashFiles('build/test-results/test/*.xml') != ''
      with:
        name: 'Test Results'
        path: 'build/test-results/test/*.xml'
        reporter: 'java-junit'
        fail-on-error: false

    # 테스트 커버리지 리포트 (선택사항)
    - name: Generate Test Coverage Report
      run: ./gradlew jacocoTestReport
      continue-on-error: true

    # 빌드 아티팩트 저장 (JAR 파일) - 빌드 성공 시에만
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      if: success() && hashFiles('build/libs/*.jar') != ''
      with:
        name: tetris-jar
        path: build/libs/*.jar

    # 테스트 실패 시 로그 업로드 - 실제 로그가 존재할 때만
    - name: Upload test logs on failure
      uses: actions/upload-artifact@v4
      if: failure() && (hashFiles('build/reports/tests/test/**/*') != '' || hashFiles('build/test-results/test/**/*') != '')
      with:
        name: test-logs
        path: |
          build/reports/tests/test/
          build/test-results/test/

  # 정적 코드 분석 (선택사항)
  static-analysis:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    # 코드 스타일 검사
    - name: Run checkstyle
      run: ./gradlew checkstyleMain checkstyleTest
      continue-on-error: true

    # SpotBugs 정적 분석 (선택사항)
    - name: Run SpotBugs
      run: ./gradlew spotbugsMain spotbugsTest
      continue-on-error: true